name: Laravel

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: kanban
      DB_USERNAME: root
      DB_PASSWORD: password

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: kanban
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1.12"
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      # - name: Update Dependencies
      #   run: composer update
      # - name: dumpautoload Dependencies
      #   run: composer dumpautoload
      # - name: Link storage creating simlink folder for files
      #   run: php artisan storage:link
      # - name: Generate key
      #   run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Perform Database Migration
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate:fresh
      - name: Perform PhpUnit testing
        run: php artisan test
      # - name: Execute tests (Unit and Feature tests) via PHPUnit | Initiate PhpUnit testing
      #   run: vendor/bin/phpunit
